const IMAGES = {
    techLogo1: require("../assets/img/technologies/1.png"),
    techLogo2: require('../assets/img/technologies/2.png'),
    techLogo3: require('../assets/img/technologies/3.png'),
    techLogo4: require('../assets/img/technologies/4.png'),
    techLogo5: require('../assets/img/technologies/5.png'),
    techLogo6: require('../assets/img/technologies/6.png'),
    techLogo7: require('../assets/img/technologies/7.png'),
    techLogo8: require('../assets/img/technologies/8.png'),
    techLogo9: require('../assets/img/technologies/9.png'),
    techLogo10: require('../assets/img/technologies/10.png'),
    techLogo11: require('../assets/img/technologies/11.png'),
    techLogo12: require('../assets/img/technologies/12.png'),
    techLogo13: require('../assets/img/technologies/13.png'),
    aboutImg: require('../assets/img/about-hero.svg'),
    JN: require('../assets/img/JN.png'),
    signature: require('../assets/img/signature.png'),
    Java: require('../assets/img/Java.png'),
    challenges: require('../assets/img/challenges.png'),
    learn: require('../assets/img/learn.png'),
    one: require('../assets/img/1.png'),
    two: require('../assets/img/2.png'),
    three: require('../assets/img/3.png'),
    Reactjs: require('../assets/img/tech-skills/Reactjs.png'),
    mongodb: require('../assets/img/tech-skills/mongodb.png'),
    mysql: require('../assets/img/tech-skills/mysql.png'),
    nodejs: require('../assets/img/tech-skills/nodejs.png'),
    express: require('../assets/img/tech-skills/express.png'),
    javascript: require('../assets/img/tech-skills/javascript.png'),
    HTML: require('../assets/img/tech-skills/HTML.png'),
    css: require('../assets/img/tech-skills/css.png'),
    bootstrap: require('../assets/img/tech-skills/bootstrap.png'),
    Workethic: require('../assets/img/soft-skills/Workethic.png'),
    timemanagement: require('../assets/img/soft-skills/timemanagement.png'),
    communication: require('../assets/img/soft-skills/communication.png'),
    problemSolving: require('../assets/img/soft-skills/problem-solving.png'),
    teamwork: require('../assets/img/soft-skills/teamwork.png'),
    creativity: require('../assets/img/soft-skills/creativity.png'),
    CoMed: require('../assets/img/CoMed.png'),
    eCommerce: require('../assets/img/eCommerce.jpg'),
    library: require('../assets/img/library.png'),
    Marvel: require('../assets/img/Marvel.png'),
    MyDriver: require('../assets/img/My-Driver.jpg'),
    selfcheckout: require('../assets/img/selfcheckout.png'),

}

export default IMAGES;